node Class Reference
node Class Reference
Public Member Functions
node ()
node (string name1, int temp)
int getIndegree ()
string getName ()
vector< node > getOutgoing ()
void setIndegree (int temp)
void setName (string temp)
void setOutgoing (vector< node > temp)
void print ()
Constructor & Destructor Documentation
node::node () [inline]
node::node (string name1, int temp) [inline]
Member Function Documentation
int node::getIndegree () [inline]
Referenced by findLeastNode(), and main().
string node::getName () [inline]
Referenced by findLeastNode().
vector<node> node::getOutgoing () [inline]
Referenced by main().
void node::print () [inline]
Referenced by main().
void node::setIndegree (int temp) [inline]
Referenced by main().
void node::setName (string temp) [inline]
void node::setOutgoing (vector< node > temp) [inline]
Referenced by main().
The documentation for this class was generated from the following file:
topological.cpp