topological.cpp File Reference
topological.cpp File Reference
#include <iostream>
#include <algorithm>
#include <fstream>
#include <stdlib.h>
#include <cstdlib>
#include <stdio.h>
#include <vector>
Classes
class node
Functions
node * getNode (string name, vector< node > courses)
bool hasNode (string name, vector< node > courses)
node * findLeastNode (vector< node >courses)
int main (int argc, char **argv)
Function Documentation
node * findLeastNode (vector< node > courses)
References node::getIndegree(), and node::getName().
Referenced by main().
node * getNode (string name, vector< node > courses)
Referenced by main().
bool hasNode (string name, vector< node > courses)
Referenced by main().
int main (int argc, char ** argv)
References findLeastNode(), node::getIndegree(), getNode(), node::getOutgoing(), hasNode(), node::print(), node::setIndegree(), and node::setOutgoing().